// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rolling_median_cpp
NumericVector rolling_median_cpp(NumericVector x, int hws, bool replicate, double pad_value);
RcppExport SEXP _zeitR_rolling_median_cpp(SEXP xSEXP, SEXP hwsSEXP, SEXP replicateSEXP, SEXP pad_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type hws(hwsSEXP);
    Rcpp::traits::input_parameter< bool >::type replicate(replicateSEXP);
    Rcpp::traits::input_parameter< double >::type pad_value(pad_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_median_cpp(x, hws, replicate, pad_value));
    return rcpp_result_gen;
END_RCPP
}
// rolling_mean_cpp
NumericVector rolling_mean_cpp(NumericVector x, int hws, bool replicate, double pad_value);
RcppExport SEXP _zeitR_rolling_mean_cpp(SEXP xSEXP, SEXP hwsSEXP, SEXP replicateSEXP, SEXP pad_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type hws(hwsSEXP);
    Rcpp::traits::input_parameter< bool >::type replicate(replicateSEXP);
    Rcpp::traits::input_parameter< double >::type pad_value(pad_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_mean_cpp(x, hws, replicate, pad_value));
    return rcpp_result_gen;
END_RCPP
}
// rolling_var_cpp
NumericVector rolling_var_cpp(NumericVector x, int hws, bool replicate, double pad_value);
RcppExport SEXP _zeitR_rolling_var_cpp(SEXP xSEXP, SEXP hwsSEXP, SEXP replicateSEXP, SEXP pad_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type hws(hwsSEXP);
    Rcpp::traits::input_parameter< bool >::type replicate(replicateSEXP);
    Rcpp::traits::input_parameter< double >::type pad_value(pad_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_var_cpp(x, hws, replicate, pad_value));
    return rcpp_result_gen;
END_RCPP
}
// rolling_zero_prop_cpp
NumericVector rolling_zero_prop_cpp(NumericVector x, int hws, double pad_value);
RcppExport SEXP _zeitR_rolling_zero_prop_cpp(SEXP xSEXP, SEXP hwsSEXP, SEXP pad_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type hws(hwsSEXP);
    Rcpp::traits::input_parameter< double >::type pad_value(pad_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_zero_prop_cpp(x, hws, pad_value));
    return rcpp_result_gen;
END_RCPP
}
// rolling_quantile_cpp
NumericVector rolling_quantile_cpp(NumericVector x, int hws, double q, bool replicate, double pad_value);
RcppExport SEXP _zeitR_rolling_quantile_cpp(SEXP xSEXP, SEXP hwsSEXP, SEXP qSEXP, SEXP replicateSEXP, SEXP pad_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type hws(hwsSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type replicate(replicateSEXP);
    Rcpp::traits::input_parameter< double >::type pad_value(pad_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_quantile_cpp(x, hws, q, replicate, pad_value));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_zeitR_rolling_median_cpp", (DL_FUNC) &_zeitR_rolling_median_cpp, 4},
    {"_zeitR_rolling_mean_cpp", (DL_FUNC) &_zeitR_rolling_mean_cpp, 4},
    {"_zeitR_rolling_var_cpp", (DL_FUNC) &_zeitR_rolling_var_cpp, 4},
    {"_zeitR_rolling_zero_prop_cpp", (DL_FUNC) &_zeitR_rolling_zero_prop_cpp, 3},
    {"_zeitR_rolling_quantile_cpp", (DL_FUNC) &_zeitR_rolling_quantile_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_zeitR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
