# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rolling_median_cpp <- function(x, hws, replicate = TRUE, pad_value = 0.0) {
    .Call(`_zeitR_rolling_median_cpp`, x, hws, replicate, pad_value)
}

rolling_mean_cpp <- function(x, hws, replicate = TRUE, pad_value = 0.0) {
    .Call(`_zeitR_rolling_mean_cpp`, x, hws, replicate, pad_value)
}

rolling_var_cpp <- function(x, hws, replicate = TRUE, pad_value = 0.0) {
    .Call(`_zeitR_rolling_var_cpp`, x, hws, replicate, pad_value)
}

rolling_zero_prop_cpp <- function(x, hws, pad_value = 1.0) {
    .Call(`_zeitR_rolling_zero_prop_cpp`, x, hws, pad_value)
}

rolling_quantile_cpp <- function(x, hws, q = 0.6, replicate = TRUE, pad_value = 0.0) {
    .Call(`_zeitR_rolling_quantile_cpp`, x, hws, q, replicate, pad_value)
}

